-- ValMan Supabase core schema v0.1
-- Local-first compatible backend for ValMan 0.6.x -> future 0.7+

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  employee_id text not null unique,
  name text not null,
  role text not null check (role in ('ADMIN','MECCANICO','ELETTRICO','LETTURA')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_invites (
  employee_id text primary key,
  name text not null,
  role text not null check (role in ('MECCANICO','ELETTRICO','LETTURA')),
  enabled boolean not null default true,
  activation_hash text not null,
  claimed_by uuid references auth.users(id) on delete set null,
  claimed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.records (
  collection text not null check (collection in (
    'machines','faults','interventions','leaves','communications','handovers',
    'documents','shifts','turnationImages','turnationOcr'
  )),
  record_key text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  primary key (collection, record_key)
);

create index if not exists idx_records_collection on public.records(collection);
create index if not exists idx_records_updated_at on public.records(updated_at);
create index if not exists idx_records_data_gin on public.records using gin(data);

create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  original_name text not null,
  mime text,
  machine text,
  storage_path text not null unique,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  openai_file_id text
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.valman_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles
for each row execute function public.valman_touch_updated_at();

drop trigger if exists trg_employee_invites_updated_at on public.employee_invites;
create trigger trg_employee_invites_updated_at before update on public.employee_invites
for each row execute function public.valman_touch_updated_at();

create or replace function public.valman_is_enabled()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.enabled = true
  );
$$;

create or replace function public.valman_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.enabled = true and p.role = 'ADMIN'
  );
$$;

grant execute on function public.valman_is_enabled() to authenticated;
grant execute on function public.valman_is_admin() to authenticated;

-- Admin creates an employee ID and receives a one-time activation code.
create or replace function public.admin_create_employee(
  p_employee_id text,
  p_name text,
  p_role text
)
returns table(employee_id text, activation_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id text;
  v_code text;
  v_role text;
begin
  if not public.valman_is_admin() then
    raise exception 'ADMIN_REQUIRED';
  end if;

  v_id := upper(regexp_replace(trim(coalesce(p_employee_id,'')), '[^A-Z0-9_.-]', '', 'g'));
  if length(v_id) < 2 then raise exception 'INVALID_EMPLOYEE_ID'; end if;
  if trim(coalesce(p_name,'')) = '' then raise exception 'NAME_REQUIRED'; end if;

  v_role := upper(coalesce(p_role,'LETTURA'));
  if v_role not in ('MECCANICO','ELETTRICO','LETTURA') then v_role := 'LETTURA'; end if;

  v_code := upper(substr(encode(gen_random_bytes(8),'hex'), 1, 10));

  insert into public.employee_invites(
    employee_id,name,role,enabled,activation_hash,created_by
  ) values (
    v_id,trim(p_name),v_role,true,encode(digest(v_code,'sha256'),'hex'),auth.uid()
  )
  on conflict (employee_id) do update set
    name = excluded.name,
    role = excluded.role,
    enabled = true,
    activation_hash = excluded.activation_hash,
    claimed_by = null,
    claimed_at = null,
    created_by = auth.uid(),
    updated_at = now();

  insert into public.audit_log(user_id,action,entity,entity_id,details)
  values(auth.uid(),'CREATE_EMPLOYEE_INVITE','employee',v_id,jsonb_build_object('role',v_role));

  return query select v_id, v_code;
end;
$$;

grant execute on function public.admin_create_employee(text,text,text) to authenticated;

alter table public.profiles enable row level security;
alter table public.employee_invites enable row level security;
alter table public.records enable row level security;
alter table public.attachments enable row level security;
alter table public.audit_log enable row level security;

-- Profiles: all enabled ValMan users can see colleague name/role; only admins modify them.
drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated
using (public.valman_is_enabled());

drop policy if exists profiles_admin_write on public.profiles;
create policy profiles_admin_write on public.profiles for all to authenticated
using (public.valman_is_admin())
with check (public.valman_is_admin());

-- Invites are administrative only. Claiming happens through the Edge Function.
drop policy if exists invites_admin on public.employee_invites;
create policy invites_admin on public.employee_invites for all to authenticated
using (public.valman_is_admin())
with check (public.valman_is_admin());

-- Shared workspace. App-level roles can be tightened later without changing the data format.
drop policy if exists records_read on public.records;
create policy records_read on public.records for select to authenticated
using (public.valman_is_enabled());

drop policy if exists records_insert on public.records;
create policy records_insert on public.records for insert to authenticated
with check (public.valman_is_enabled() and updated_by = auth.uid());

drop policy if exists records_update on public.records;
create policy records_update on public.records for update to authenticated
using (public.valman_is_enabled())
with check (public.valman_is_enabled() and updated_by = auth.uid());

drop policy if exists records_delete on public.records;
create policy records_delete on public.records for delete to authenticated
using (public.valman_is_enabled());

-- Shared documents/photos metadata.
drop policy if exists attachments_read on public.attachments;
create policy attachments_read on public.attachments for select to authenticated
using (public.valman_is_enabled());

drop policy if exists attachments_insert on public.attachments;
create policy attachments_insert on public.attachments for insert to authenticated
with check (public.valman_is_enabled() and created_by = auth.uid());

drop policy if exists attachments_update on public.attachments;
create policy attachments_update on public.attachments for update to authenticated
using (public.valman_is_enabled())
with check (public.valman_is_enabled());

drop policy if exists attachments_delete on public.attachments;
create policy attachments_delete on public.attachments for delete to authenticated
using (public.valman_is_enabled());

-- Audit: users can append their own events; only admin can read the full log.
drop policy if exists audit_insert on public.audit_log;
create policy audit_insert on public.audit_log for insert to authenticated
with check (public.valman_is_enabled() and user_id = auth.uid());

drop policy if exists audit_admin_read on public.audit_log;
create policy audit_admin_read on public.audit_log for select to authenticated
using (public.valman_is_admin());

-- Private shared storage bucket for manuals, photos and schematics.
insert into storage.buckets(id,name,public,file_size_limit)
values ('valman-files','valman-files',false,52428800)
on conflict (id) do update set public=false, file_size_limit=52428800;

drop policy if exists valman_storage_read on storage.objects;
create policy valman_storage_read on storage.objects for select to authenticated
using (bucket_id='valman-files' and public.valman_is_enabled());

drop policy if exists valman_storage_insert on storage.objects;
create policy valman_storage_insert on storage.objects for insert to authenticated
with check (bucket_id='valman-files' and public.valman_is_enabled());

drop policy if exists valman_storage_update on storage.objects;
create policy valman_storage_update on storage.objects for update to authenticated
using (bucket_id='valman-files' and public.valman_is_enabled())
with check (bucket_id='valman-files' and public.valman_is_enabled());

drop policy if exists valman_storage_delete on storage.objects;
create policy valman_storage_delete on storage.objects for delete to authenticated
using (bucket_id='valman-files' and public.valman_is_enabled());
